-- V1__init.sql (PostgreSQL)

-- 1) users
CREATE TABLE IF NOT EXISTS users (
  uid              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         VARCHAR(20)  NOT NULL,
  login_id         VARCHAR(30),
  password         VARCHAR(60),
  email            VARCHAR(30),
  role             VARCHAR(20)  NOT NULL,
  provider         VARCHAR(255),
  provider_id      VARCHAR(255),
  failed_attempts  INTEGER      NOT NULL DEFAULT 0,
  last_failed_at   TIMESTAMP(6) WITH TIME ZONE,
  locked_until     TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_login_id               ON users (login_id);
CREATE INDEX IF NOT EXISTS idx_email                  ON users (email);
CREATE INDEX IF NOT EXISTS idx_provider_providerId    ON users (provider, provider_id);

-- 2) refresh_tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_id     VARCHAR(255),
  token_hash   VARCHAR(128) NOT NULL,
  fingerprint  VARCHAR(255),
  expires_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  persistent   BOOLEAN,
  revoked      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_tokenHash             ON refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_expiresAt             ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_loginId_fingerprint   ON refresh_tokens (login_id, fingerprint);
