-- ===========================
-- 1) games
-- ===========================
CREATE TABLE IF NOT EXISTS games (
  game_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         BIGINT      NOT NULL,        -- FK to users(uid)
  game_name   VARCHAR(255) NOT NULL
);

-- FK
ALTER TABLE games
  ADD CONSTRAINT fk_games_user
  FOREIGN KEY (uid) REFERENCES users (uid);

-- Unique (user별 게임명 유니크)
CREATE UNIQUE INDEX IF NOT EXISTS uq_games_uid_game_name
  ON games (uid, game_name);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_uid ON games (uid);

-- ===========================
-- 2) homeworks
-- ===========================
CREATE TABLE IF NOT EXISTS homeworks (
  homework_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gameId         BIGINT       NOT NULL,           -- @JoinColumn(name="gameId")
  homework_title VARCHAR(255) NOT NULL,
  homework_memo  VARCHAR(255),
  homework_type  VARCHAR(50)  NOT NULL            -- Enum STRING 저장
);

-- FK: homeworks.gameId -> games.game_id
ALTER TABLE homeworks
  ADD CONSTRAINT fk_homeworks_game
  FOREIGN KEY (gameId) REFERENCES games (game_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_game_id ON homeworks (gameId);

-- ===========================
-- 3) history
-- ===========================
CREATE TABLE IF NOT EXISTS history (
  history_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         BIGINT    NOT NULL,      -- @JoinColumn(name="uid")
  homeworkId  BIGINT    NOT NULL,      -- @JoinColumn(name="homeworkId")
  start_date  DATE      NOT NULL,
  end_date    DATE      NOT NULL,
  done        BOOLEAN   NOT NULL
);

-- FKs
ALTER TABLE history
  ADD CONSTRAINT fk_history_user
  FOREIGN KEY (uid) REFERENCES users (uid);

ALTER TABLE history
  ADD CONSTRAINT fk_history_homework
  FOREIGN KEY (homeworkId) REFERENCES homeworks (homework_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_id     ON history (uid);
CREATE INDEX IF NOT EXISTS idx_homework_id ON history (homeworkId);
CREATE INDEX IF NOT EXISTS idx_start_end   ON history (start_date, end_date);
