spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailyquest
    username: hoje
    password: hj13579!@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  #실행 중인 JPA SQL 쿼리문을 콘솔에 출력
  profiles:
    active: local

jwt:
  secret: rcy9o6zfrlklmnrizszaanolcmfjdrac
  expiration: 3600000


server:
  port: 8080