spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: ${REDIS_SSL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres


  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          client-secret: ${KAKAO_CLIENT_SECRET}
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}

  api:
    base-url: https://api.dailyquest.app/api

  # 운영 CORS: 배포 도메인만
  cors:
    allowed-origins: https://dailyquest.app
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    allow-credentials: true
    max-age: 3600

  springdoc:
    swagger-ui:
      enabled: false    # 운영에서 UI 차단 권장
    api-docs:
      enabled: false    # 필요시 프록시/인증 뒤에 둠

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: never

  server:
    forward-headers-strategy: native
    compression:
      enabled: true
      mime-types: application/json,application/javascript,text/html,text/plain,text/css
      min-response-size: 1024
    error:
      whitelabel:
        enabled: false

  logging:
    level:
      root: INFO
      org.hibernate.SQL: WARN
      org.springframework.security: INFO
      com.dailyquest: INFO