spring:
  application:
    name: dailyquest

  config:
    import: optional:file:.env[.properties]

  jpa:
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul


  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    access-secret: ${JWT_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-ttl: ${JWT_ACCESS_TTL}
    refresh-ttl: ${JWT_REFRESH_TTL}
    expiration: 3600000

  security:
    login-limit:
      account-window-seconds: 600      # 계정 실패 집계 윈도우(10분)
      account-soft-threshold: 5        # 소프트락(캡차/지연/임시락 전 단계) 기준
      account-soft-lock-seconds: 900   # 소프트락 유지(15분)
      account-hard-threshold: 10       # 하드락 기준
      account-hard-lock-seconds: 43200 # 하드락 유지(12시간)

      ip-window-seconds: 600           # IP 집계 윈도우(10분)
      ip-threshold: 20                 # IP 과도 실패 기준
      ip-cooldown-seconds: 3600        # IP 쿨다운(1시간)

    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ "profile", "email" ]
          kakao:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: [ "profile_nickname" ]
            provider: "kakao"
          naver:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: [ "name" ]
            provider: "naver"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: "/**"

  server:
    port: 8080
    servlet:
      session:
        cookie:
          same-site: none   # Refresh 쿠키 전략과 일치
      forward-headers-strategy: framework  # 프록시/HTTPS 헤더 신뢰

    # 공통: Actuator 최소 노출
    management:
      endpoints:
        web:
          exposure:
            include: health
      endpoint:
        health:
          show-details: never
    mvc:
      cors:
        mappings:
          - path-pattern: /api/**

