spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamemanager
    username: root
    password: hj13579
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  #실행 중인 JPA SQL 쿼리문을 콘솔에 출력
  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


server:
  port: 8080