spring:

  server:
    port: ${PORT:8080}
    servlet:
      session:
        cookie:
          secure: true
          same-site: lax    # (지금 타임리프면 Lax로 충분 / 나중에 React 분리 시 none)
    forward-headers-strategy: framework

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}         # 예: jdbc:mysql://dev-db:3306/dailyquest
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # (권장) Flyway로 스키마 관리
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
    open-in-view: false


  flyway:
    location: classpath:db/migration/postgres
    enabled: true

  data:
    redis:
      url: ${REDIS_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          client-secret: ${KAKAO_CLIENT_SECRET}
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}

  api:
    base-url: https://dev.api.dailyquest.app/api

  cors:
    path-pattern: /api/**
    allowed-origins: ${CORS_ALLOWED}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true

  management:
    endpoints.web.exposure.include: health,metrics
    endpoint.health.show-details: when_authorized

  logging:
    level:
      root: INFO
      org:
        flywaydb: DEBUG
        hibernate.tool.hbm2ddl: DEBUG