spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailyquest
    username: hoje
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  #실행 중인 JPA SQL 쿼리문을 콘솔에 출력
  profiles:
    active: local
  mail:
    host: smtp.gmail.com  #Gmail의 SMTP 서버 주소
    port: 587             #Gmail SMTP 서버가 사용하는 STARTTLS 포트 번호
    username: ${EMAIL_USERNAME}   #메일을 보내는 계정의 이메일 주소
    password: ${EMAIL_PASSWORD}   #메일을 보내는 계정의 비밀번호
    properties:
      mail.smtp.auth: true        #SMTP 인증을 사용
      mail.smtp.starttls.enable: true   #STARTTLS는 일반 연결을 암호화된 연결로 전환하는 기능
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: "/**"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


server:
  port: 8080