spring:
  server:
    port: 8080
    servlet:
      session:
        cookie:
          same-site: lax   # 로컬에선 lax 권장(HTTPS가 아닐 수 있어서)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}          #Gmail의 SMTP 서버 주소
    port: ${MAIL_PORT}             #Gmail SMTP 서버가 사용하는 STARTTLS 포트 번호
    username: ${EMAIL_USERNAME}   #메일을 보내는 계정의 이메일 주소
    password: ${EMAIL_PASSWORD}   #메일을 보내는 계정의 비밀번호
    properties:
      mail.smtp.auth: false        #SMTP 인증을 사용
      mail.smtp.starttls.enable: false   #STARTTLS는 일반 연결을 암호화된 연결로 전환하는 기능

  docker:
    compose:
      enabled: true       # 감지/시작
      file: "E:/gamemanager/dailyquest/compose.yml"  # 위치
      lifecycle-management: start-only  # 개발 중엔 컨테이너 계속 살려두고 싶으면 주석 해제


  api:
    base-url: http://localhost:8080/api

  # CORS: 로컬 프론트만 허용
  cors:
    allowed-origins:
      - http://localhost:8080
      - "http://127.0.0.1:3000"
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  management:
    endpoints.web.exposure.include: health,metrics
    endpoint.health.show-details: always

  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.springframework.security: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE