spring:
  application:
    name: dailyquest

  mvc:
    cors:
      mappings:
        - path-pattern: /api/**

  jpa:
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          google:
              redirect-uri: "{baseUrl}/login/oauth2/code/google"
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope: [ "profile", "email" ]
          kakao:
              client-authentication-method: client_secret_post
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
              client-id: ${KAKAO_CLIENT_ID}
              client-secret: ${KAKAO_CLIENT_SECRET}
              scope: [ "profile_nickname" ]
              provider: "kakao"
          naver:
              client-authentication-method: client_secret_post
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/naver"
              client-id: ${NAVER_CLIENT_ID}
              client-secret: ${NAVER_CLIENT_SECRET}
              scope: [ "name" ]
              provider: "naver"
        provider:
          kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
          naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: "/**"

server:
    port: 8080
    servlet:
      session:
        cookie:
          same-site: none   # Refresh 쿠키 전략과 일치
      forward-headers-strategy: framework  # 프록시/HTTPS 헤더 신뢰

    # 공통: Actuator 최소 노출
management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


