name: CI Backend

on:
  push:
    branches: [ "dev", "feature/**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
    steps:
      - uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD = $(pwd)"
          echo "Listing root:"
          ls -la
          echo "Listing gradle wrapper dir:"
          ls -la gradle || true
          ls -la gradle/wrapper || true
          echo "Gradle wrapper file:"
          ls -la gradlew || true

      - name: Debug resources
        run: |
          ls -R src/test/resources
          echo "====="
          cat src/test/resources/application-test.yml || true


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew clean build --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: be-test-reports
          path: build/reports/tests/test/
