name: CI Backend

on:
  push:
    branches: [ "dev", "feature/**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew clean build --stacktrace
env:
  SPRING_PROFILES_ACTIVE: test
