name: CI Backend

on:
  push:
    branches: [ "dev", "feature/**" ]
    paths:
      - "src/**"
      - "build.gradle"
      - "build.gradle.kts"
      - "settings.gradle"
      - "settings.gradle.kts"
      - "gradle/**"
      - ".github/workflows/ci-be.yml"
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - "src/**"
      - "build.gradle"
      - "build.gradle.kts"
      - "settings.gradle"
      - "settings.gradle.kts"
      - "gradle/**"
      - ".github/workflows/ci-be.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('build.gradle') != '' || hashFiles('build.gradle.kts') != '' }}
    env:
      SPRING_PROFILES_ACTIVE: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew clean build --stacktrace

      - name: Upload test reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: be-test-reports
          path: |
            build/test-results/test/
            build/reports/tests/test/
env:
  SPRING_PROFILES_ACTIVE: test
